Consistency fixes
Standardizing on `type -p sudo` use should make it easier to use sudo
alternatives. (IIRC this was requested a long time ago via email, but
that email went poof.)

Signed-off-by: Daniel M. Capella <polyzen@archlinux.org>

diff --git a/src/checkupdates.sh.in b/src/checkupdates.sh.in
--- a/src/checkupdates.sh.in
+++ b/src/checkupdates.sh.in
@@ -40,11 +40,11 @@ die() {
 
 runcmd() {
 	if (( EUID != 0 )); then
-		msg 'Escalating privileges using sudo'
-		if sudo -v &>/dev/null && sudo -l &>/dev/null; then
-			sudo "$@"
+		if ! type -p sudo; then
+			error 'Cannot find the sudo binary!'
+			die "Either install \"sudo\" or run as root."
 		else
-			die 'Failed to escalate'
+			sudo "$@"
 		fi
 	else
 		"$@"
diff --git a/src/paccache.sh.in b/src/paccache.sh.in
--- a/src/paccache.sh.in
+++ b/src/paccache.sh.in
@@ -33,7 +33,7 @@ declare -i min_atime=0 min_mtime=0
 declare    delim=$'\n' keep=3 movedir='' scanarch=''
 
 QUIET=0
-USE_COLOR='y'
+USE_COLOR=1
 
 # Import libmakepkg
 # shellcheck source=/dev/null
@@ -141,11 +141,11 @@ m4_include(../lib/size_to_human.sh)
 
 runcmd() {
 	if (( needsroot && EUID != 0 )); then
-		msg 'Escalating privileges using sudo'
-		if sudo -v &>/dev/null && sudo -l &>/dev/null; then
-			sudo "$@"
+		if ! type -p sudo; then
+			error 'Cannot find the sudo binary!'
+			die 'Either install "sudo" or run as root.'
 		else
-			die 'Failed to escalate'
+			sudo "$@"
 		fi
 	else
 		"$@"
@@ -290,7 +290,7 @@ while :; do
 			move=1 movedir=$2
 			shift ;;
 		--nocolor)
-			USE_COLOR='n' ;;
+			USE_COLOR=0 ;;
 		-z|--null)
 			delim='\0' ;;
 		-q|--quiet)
@@ -319,7 +319,7 @@ while :; do
 done
 
 # check if messages are to be printed using color
-if [[ -t 2 && $USE_COLOR != "n" ]]; then
+if [[ -t 2 ]] && (( USE_COLOR )); then
 	colorize
 else
 	unset ALL_OFF BOLD BLUE GREEN RED YELLOW
diff --git a/src/pacscripts.sh.in b/src/pacscripts.sh.in
--- a/src/pacscripts.sh.in
+++ b/src/pacscripts.sh.in
@@ -20,17 +20,20 @@
 #   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #
 
-# bash options
-set -o nounset
-set -o errexit
-
 declare -r myname='pacscripts'
 declare -r myver='@PACKAGE_VERSION@'
 
-error() {
-	local mesg=$1; shift
-	# shellcheck disable=SC2059
-	printf "==> $(gettext "ERROR:") ${mesg}\n" "$@" >&2
+LIBRARY=${LIBRARY:-'@libmakepkgdir@'}
+
+USE_COLOR=1
+
+# Import libmakepkg
+# shellcheck source=/dev/null
+source "$LIBRARY"/util/message.sh
+
+die() {
+	error "$@"
+	exit 1
 }
 
 usage() {
@@ -42,6 +45,7 @@ Print the {pre,post}_{install,remove,upgrade} scripts of a given package.
 Usage: ${myname} <pkgname | pkgfile>
 
 Options:
+  -m, --nocolor  do not colorize output
   -h, --help     show this help message and exit
   -V, --version  display version information and exit
 
@@ -52,8 +56,7 @@ EOF
 
 
 if ! DBPath="$(pacman-conf DBPath)"; then
-	error "unable to read @sysconfdir@/pacman.conf"
-	exit 1
+	die "Unable to read @sysconfdir@/pacman.conf"
 fi
 pac_db="${DBPath:-@localstatedir@/lib/pacman}/local"
 
@@ -63,19 +66,25 @@ version() {
 	echo 'Copyright (c) 2009 Xavier Chantry <shiningxc@gmail.com>'
 }
 
-spacman() {
-	if [ $EUID -eq 0 ]; then
-		pacman "$@"
-	else
+runcmd() {
+	if (( EUID != 0 )); then
 		if ! type -p sudo; then
-			error "Cannot find the sudo binary!"
-			error "${myname} requires root privileges. Either install \"sudo\" or run as root."
-			exit 1
+			error 'Cannot find the sudo binary!'
+			die "${myname} requires root privileges. Either install \"sudo\" or run as root."
 		else
-			sudo pacman "$@"
+			sudo "$@"
 		fi
+	else
+		"$@"
 	fi
 }
+
+# check if messages are to be printed using color
+if [[ -t 2 ]] && (( USE_COLOR )); then
+	colorize
+else
+	unset ALL_OFF BOLD BLUE GREEN RED YELLOW
+fi
 
 print_db() {
 	pkg=$(pacman -Q "$1")
@@ -117,7 +126,7 @@ print_scriptlet() {
 	fi
 	url=$(pacman -Sddp "$1")
 	if [[ $url != file://* ]]; then
-		if ! spacman -Sddw --logfile /dev/null --noconfirm "$1" >&2; then
+		if ! runcmd pacman -Sddw --logfile /dev/null --noconfirm "$1" >&2; then
 			error "Failed to download $1"
 			return 1
 		fi
@@ -134,6 +143,7 @@ if [ $# -ne 1 ] ; then
 fi
 
 case "$1" in
+	-m|--nocolor) USE_COLOR=0; shift ;;
 	--help|-h) usage; exit 0 ;;
 	--version|-V) version; exit 0 ;;
 	*) print_scriptlet "$1" ;;
